import { stringify as yamlStringify } from "yaml";
import type { Locator, Outcome, Spec, Step } from "../schema/spec.v1";

export interface ImportPlaywrightResult {
  spec: Spec;
  yaml: string;
  todos: string[];
}

export interface ImportPlaywrightOptions {
  sourcePath?: string;
}

export function importPlaywright(
  source: string,
  opts: ImportPlaywrightOptions = {},
): ImportPlaywrightResult {
  const test = findFirstTest(source);
  const title = test?.title ?? "Imported Playwright test";
  const lines = (test?.body ?? source).split("\n");
  const steps: Step[] = [];
  const outcomes: Outcome[] = [];
  const todos: string[] = [];

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (shouldIgnore(line)) continue;

    const mappedStep = mapStep(line);
    if (mappedStep) {
      steps.push(mappedStep);
      continue;
    }

    const mappedOutcome = mapOutcome(line, outcomes.length);
    if (mappedOutcome) {
      outcomes.push(mappedOutcome);
      continue;
    }

    todos.push(rawLine.trim());
  }

  if (outcomes.length === 0) {
    todos.push(
      "No Playwright expect() assertion mapped; replace placeholder outcome.",
    );
    outcomes.push({
      id: "todo_assertion",
      description:
        "TODO replace with the behavior this Playwright test asserts",
      verify: { text: { contains: "TODO_replace_me" } },
    });
  }

  const spec: Spec = {
    version: 1,
    name: slug(title),
    intent: title,
    mode: "normal",
    outcomes,
    ...(steps.length > 0 ? { steps } : {}),
  };

  const header = [
    "# Generated by `cairn import playwright`.",
    ...(opts.sourcePath ? [`# Source: ${opts.sourcePath}`] : []),
    "# Review TODO comments before treating this as a finished behavioral spec.",
    ...todos.map((todo) => `# TODO: ${todo}`),
    "",
  ].join("\n");

  return {
    spec,
    yaml:
      header +
      yamlStringify(spec, {
        indent: 2,
        lineWidth: 100,
        defaultStringType: "PLAIN",
        defaultKeyType: "PLAIN",
      }),
    todos,
  };
}

function findFirstTest(
  source: string,
): { title: string; body: string } | undefined {
  const re = /\btest(?:\.(\w+))?\s*\(/gm;
  let m: RegExpExecArray | null;
  while ((m = re.exec(source))) {
    if (m[1] === "describe") continue;
    const parsed = parseTestAt(source, m.index + m[0].length);
    if (parsed) return parsed;
  }
  return undefined;
}

function parseTestAt(
  source: string,
  titleStart: number,
): { title: string; body: string } | undefined {
  let i = skipWhitespace(source, titleStart);
  const quote = source[i];
  if (quote !== "'" && quote !== '"' && quote !== "`") return undefined;
  const titleEnd = readQuoted(source, i);
  if (titleEnd < 0) return undefined;
  const title = source.slice(i + 1, titleEnd);
  i = skipWhitespace(source, titleEnd + 1);
  if (source[i] !== ",") return undefined;
  const rest = source.slice(i);
  const arrow = /^,\s*async\s*(?:\([^)]*\)|[A-Za-z_$][\w$]*)\s*=>\s*\{/.exec(
    rest,
  );
  if (!arrow) return undefined;
  const bodyStart = i + arrow[0].length;
  let depth = 1;
  for (let j = bodyStart; j < source.length; j++) {
    const ch = source[j];
    if (ch === "{") depth++;
    if (ch === "}") depth--;
    if (depth === 0) {
      return { title, body: source.slice(bodyStart, j) };
    }
  }
  return { title, body: source.slice(bodyStart) };
}

function skipWhitespace(source: string, index: number): number {
  let i = index;
  while (/\s/.test(source[i] ?? "")) i++;
  return i;
}

function readQuoted(source: string, quoteIndex: number): number {
  const quote = source[quoteIndex];
  for (let i = quoteIndex + 1; i < source.length; i++) {
    if (source[i] === quote && source[i - 1] !== "\\") return i;
  }
  return -1;
}

function shouldIgnore(line: string): boolean {
  return (
    line.length === 0 ||
    line === "});" ||
    line === "}" ||
    line === "});" ||
    line.startsWith("import ") ||
    line.startsWith("//")
  );
}

function mapStep(line: string): Step | undefined {
  const goto = /^await\s+page\.goto\((.+?)\);?$/.exec(line);
  if (goto) {
    const path = literal(goto[1]!);
    if (path !== undefined) return { open: path };
  }

  const request =
    /^await\s+page\.request\.(get|post|put|patch|delete)\((.+?)\);?$/i.exec(
      line,
    );
  if (request) {
    const method = request[1]!.toUpperCase() as
      | "GET"
      | "POST"
      | "PUT"
      | "PATCH"
      | "DELETE";
    const parsed = splitTopLevelArgs(request[2]!);
    const url = literal(parsed[0] ?? "");
    if (url !== undefined) {
      const body = parseDataObject(parsed[1]);
      return {
        request: {
          method,
          url,
          ...(body !== undefined ? { body } : {}),
        },
      };
    }
  }

  const waitSelector = /^await\s+page\.waitForSelector\((.+?)\);?$/.exec(line);
  if (waitSelector) {
    const args = splitTopLevelArgs(waitSelector[1]!);
    const selector = literal(args[0] ?? "");
    if (selector !== undefined) {
      const state = objectStringProperty(args[1], "state");
      const timeoutMs = objectNumberProperty(args[1], "timeout");
      return {
        wait: {
          selector,
          ...(isWaitState(state) ? { state } : {}),
          ...(timeoutMs !== undefined ? { timeoutMs } : {}),
        },
      };
    }
  }

  const action =
    /^await\s+(page\..+?)\.(click|hover)\(\s*\);?$/.exec(line) ??
    /^await\s+(page\..+?)\.(fill|pressSequentially)\((.+?)\);?$/.exec(line);
  if (!action) return undefined;

  const loc = locator(action[1]!);
  if (!loc) return undefined;
  const op = action[2]!;
  if (op === "click") return { click: loc };
  if (op === "hover") return { hover: loc };
  // fill / pressSequentially carry a value (and pressSequentially → `type`).
  const args = splitTopLevelArgs(action[3] ?? "");
  const value = literal(args[0] ?? "");
  if (value === undefined) return undefined;
  if (op === "fill") return { fill: { ...loc, value } };
  const delayMs = objectNumberProperty(args[1], "delay");
  return {
    type: { ...loc, value, ...(delayMs !== undefined ? { delayMs } : {}) },
  };
}

function isWaitState(
  s: string | undefined,
): s is "attached" | "visible" | "hidden" | "detached" {
  return (
    s === "attached" || s === "visible" || s === "hidden" || s === "detached"
  );
}

function mapOutcome(line: string, idx: number): Outcome | undefined {
  const assertion = parseExpectAssertion(line);
  if (!assertion) return undefined;

  if (assertion.target === "page" && assertion.matcher === "toHaveURL") {
    const arg = assertion.args.trim();
    const matcher = regexLiteral(arg);
    if (matcher) {
      return outcome(idx, "url_matches", "page URL matches", {
        url: { matches: matcher },
      });
    }
    const value = literal(arg);
    if (value !== undefined) {
      return outcome(idx, "url_matches", "page URL matches", {
        url: value.startsWith("/") ? { endsWith: value } : { equals: value },
      });
    }
  }

  if (assertion.matcher === "toBeVisible") {
    const loc = locator(assertion.target);
    if (loc?.by === "selector") {
      return outcome(idx, "element_visible", "expected element is visible", {
        count: { selector: loc.selector, atLeast: 1 },
      });
    }
    if (loc?.by === "role") {
      return outcome(idx, "role_visible", "expected role is visible", {
        count: { role: loc.role, atLeast: 1 },
      });
    }
    if (loc?.by === "text") {
      // Count can't query by text; assert presence with the text verifier.
      return outcome(idx, "text_visible", "expected text is visible", {
        text: { contains: loc.text },
      });
    }
  }

  if (assertion.matcher === "toContainText") {
    const text = literal(assertion.args);
    if (text !== undefined) {
      const loc = locator(assertion.target);
      return outcome(idx, "text_contains", "expected text is present", {
        text: {
          contains: text,
          ...(loc?.by === "selector" ? { region: loc.selector } : {}),
        },
      });
    }
  }

  return undefined;
}

function outcome(
  idx: number,
  baseId: string,
  description: string,
  verify: Outcome["verify"],
): Outcome {
  return {
    id: idx === 0 ? baseId : `${baseId}_${idx + 1}`,
    description,
    verify,
  };
}

function locator(input: string): Locator | undefined {
  // A trailing `.nth(N)` selects the Nth match — strip it, parse the base
  // locator, then re-attach. Without this it was silently dropped, targeting a
  // different element than the source.
  const nthMatch = /^(.+)\.nth\((\d+)\)$/.exec(input.trim());
  const base = nthMatch ? nthMatch[1]! : input;
  const parsed = parseBaseLocator(base);
  if (!parsed) return undefined;
  // nth is a disambiguator on the semantic (role/label/text) locators; the
  // selector locator can't carry it (encode position in the CSS instead).
  if (nthMatch && parsed.by !== "selector") {
    return { ...parsed, nth: Number(nthMatch[2]) };
  }
  return parsed;
}

function parseBaseLocator(input: string): Locator | undefined {
  const receiver = "(?:[A-Za-z_$][\\w$]*\\.)?";
  const testId = new RegExp(`^${receiver}getByTestId\\((.+?)\\)$`).exec(input);
  if (testId) {
    const id = literal(testId[1]!);
    if (id !== undefined) {
      return { by: "selector", selector: `[data-testid="${cssEscape(id)}"]` };
    }
  }

  const role = new RegExp(`^${receiver}getByRole\\((.+?)\\)$`).exec(input);
  if (role) {
    const args = splitTopLevelArgs(role[1]!);
    const roleName = literal(args[0] ?? "");
    if (roleName) {
      const name = objectStringProperty(args[1], "name");
      return { by: "role", role: roleName, ...(name ? { name } : {}) };
    }
  }

  const label = new RegExp(`^${receiver}getByLabel\\((.+?)\\)$`).exec(input);
  if (label) {
    const name = literal(label[1]!);
    if (name !== undefined) return { by: "label", name };
  }

  const text = new RegExp(`^${receiver}getByText\\((.+?)\\)$`).exec(input);
  if (text) {
    const value = literal(text[1]!);
    if (value !== undefined) return { by: "text", text: value };
  }

  const selector = new RegExp(`^${receiver}locator\\((.+?)\\)$`).exec(input);
  if (selector) {
    const value = literal(selector[1]!);
    if (value !== undefined) return { by: "selector", selector: value };
  }

  return undefined;
}

interface ParsedExpectAssertion {
  target: string;
  matcher: "toHaveURL" | "toBeVisible" | "toContainText";
  args: string;
}

function parseExpectAssertion(line: string): ParsedExpectAssertion | undefined {
  const prefix = /^await\s+expect\(/.exec(line);
  if (!prefix) return undefined;
  const targetStart = prefix[0].length;
  const targetEnd = matchingParen(line, targetStart - 1);
  if (targetEnd < 0) return undefined;
  const target = line.slice(targetStart, targetEnd).trim();
  const rest = line.slice(targetEnd + 1).trim();
  const matcher = /^\.(toHaveURL|toBeVisible|toContainText)\(/.exec(rest);
  if (!matcher) return undefined;
  const argsStart = matcher[0].length;
  const argsEnd = matchingParen(rest, argsStart - 1);
  if (argsEnd < 0) return undefined;
  const tail = rest.slice(argsEnd + 1).trim();
  if (tail && tail !== ";") return undefined;
  return {
    target,
    matcher: matcher[1] as ParsedExpectAssertion["matcher"],
    args: rest.slice(argsStart, argsEnd).trim(),
  };
}

function matchingParen(input: string, openIndex: number): number {
  let depth = 0;
  let quote: string | undefined;
  for (let i = openIndex; i < input.length; i++) {
    const ch = input[i]!;
    const prev = input[i - 1];
    if (quote) {
      if (ch === quote && prev !== "\\") quote = undefined;
      continue;
    }
    if (ch === "'" || ch === '"' || ch === "`") {
      quote = ch;
      continue;
    }
    if (ch === "(") depth++;
    if (ch === ")") {
      depth--;
      if (depth === 0) return i;
    }
  }
  return -1;
}

function literal(input: string): string | undefined {
  const trimmed = input.trim();
  const m = /^(['"`])([\s\S]*)\1$/.exec(trimmed);
  return m?.[2];
}

function regexLiteral(input: string): string | undefined {
  const m = /^\/(.+)\/[a-z]*$/.exec(input.trim());
  return m?.[1];
}

function objectStringProperty(
  input: string | undefined,
  prop: string,
): string | undefined {
  if (!input) return undefined;
  const re = new RegExp(`${prop}\\s*:\\s*(['"\`])([\\s\\S]*?)\\1`);
  return re.exec(input)?.[2];
}

function objectNumberProperty(
  input: string | undefined,
  prop: string,
): number | undefined {
  if (!input) return undefined;
  const m = new RegExp(`${prop}\\s*:\\s*(\\d+)`).exec(input);
  return m ? Number(m[1]) : undefined;
}

function parseDataObject(input: string | undefined): unknown {
  if (!input) return undefined;
  const data = /(?:^|[,{]\s*)data\s*:\s*({[\s\S]*?})\s*(?:,|})/.exec(
    input,
  )?.[1];
  if (!data) return undefined;
  try {
    return JSON.parse(
      data
        .replace(/([{,]\s*)([A-Za-z_$][\w$]*)\s*:/g, '$1"$2":')
        .replace(/'/g, '"'),
    );
  } catch {
    return undefined;
  }
}

function splitTopLevelArgs(input: string): string[] {
  const args: string[] = [];
  let current = "";
  let depth = 0;
  let quote: string | undefined;
  for (let i = 0; i < input.length; i++) {
    const ch = input[i]!;
    const prev = input[i - 1];
    if (quote) {
      current += ch;
      if (ch === quote && prev !== "\\") quote = undefined;
      continue;
    }
    if (ch === "'" || ch === '"' || ch === "`") {
      quote = ch;
      current += ch;
      continue;
    }
    if (ch === "{" || ch === "(" || ch === "[") depth++;
    if (ch === "}" || ch === ")" || ch === "]") depth--;
    if (ch === "," && depth === 0) {
      args.push(current.trim());
      current = "";
      continue;
    }
    current += ch;
  }
  if (current.trim()) args.push(current.trim());
  return args;
}

function cssEscape(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function slug(title: string): string {
  const s = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  const withLetter = /^[a-z]/.test(s) ? s : `imported_${s}`;
  return withLetter.slice(0, 80) || "imported_playwright";
}
