import { stringify as yamlStringify } from "yaml";
import type { Locator, Outcome, Spec, Step } from "../schema/spec.v1";

export interface ImportPlaywrightResult {
  spec: Spec;
  yaml: string;
  todos: string[];
}

export interface ImportPlaywrightOptions {
  sourcePath?: string;
}

export function importPlaywright(
  source: string,
  opts: ImportPlaywrightOptions = {},
): ImportPlaywrightResult {
  const test = findFirstTest(source);
  const title = test?.title ?? "Imported Playwright test";
  const lines = (test?.body ?? source).split("\n");
  const steps: Step[] = [];
  const outcomes: Outcome[] = [];
  const todos: string[] = [];

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (shouldIgnore(line)) continue;

    const mappedStep = mapStep(line);
    if (mappedStep) {
      steps.push(mappedStep);
      continue;
    }

    const mappedOutcome = mapOutcome(line, outcomes.length);
    if (mappedOutcome) {
      outcomes.push(mappedOutcome);
      continue;
    }

    todos.push(rawLine.trim());
  }

  if (outcomes.length === 0) {
    todos.push(
      "No Playwright expect() assertion mapped; replace placeholder outcome.",
    );
    outcomes.push({
      id: "todo_assertion",
      description:
        "TODO replace with the behavior this Playwright test asserts",
      verify: { text: { contains: "TODO_replace_me" }, region: "page" },
    });
  }

  const spec: Spec = {
    version: 1,
    name: slug(title),
    intent: title,
    mode: "normal",
    outcomes,
    ...(steps.length > 0 ? { steps } : {}),
  };

  const header = [
    "# Generated by `cairn import playwright`.",
    ...(opts.sourcePath ? [`# Source: ${opts.sourcePath}`] : []),
    "# Review TODO comments before treating this as a finished behavioral spec.",
    ...todos.map((todo) => `# TODO: ${todo}`),
    "",
  ].join("\n");

  return {
    spec,
    yaml:
      header +
      yamlStringify(spec, {
        indent: 2,
        lineWidth: 100,
        defaultStringType: "PLAIN",
        defaultKeyType: "PLAIN",
      }),
    todos,
  };
}

function findFirstTest(
  source: string,
): { title: string; body: string } | undefined {
  const m =
    /test(?:\.\w+)?\(\s*(['"`])([\s\S]*?)\1\s*,\s*async\s*\([^)]*\)\s*=>\s*\{/m.exec(
      source,
    );
  if (!m || m.index === undefined) return undefined;
  const bodyStart = m.index + m[0].length;
  let depth = 1;
  for (let i = bodyStart; i < source.length; i++) {
    const ch = source[i];
    if (ch === "{") depth++;
    if (ch === "}") depth--;
    if (depth === 0) {
      return { title: m[2]!, body: source.slice(bodyStart, i) };
    }
  }
  return { title: m[2]!, body: source.slice(bodyStart) };
}

function shouldIgnore(line: string): boolean {
  return (
    line.length === 0 ||
    line === "});" ||
    line === "}" ||
    line === "});" ||
    line.startsWith("import ") ||
    line.startsWith("//")
  );
}

function mapStep(line: string): Step | undefined {
  const goto = /^await\s+page\.goto\((.+?)\);?$/.exec(line);
  if (goto) {
    const path = literal(goto[1]!);
    if (path !== undefined) return { open: path };
  }

  const request =
    /^await\s+page\.request\.(get|post|put|patch|delete)\((.+?)\);?$/i.exec(
      line,
    );
  if (request) {
    const method = request[1]!.toUpperCase() as
      | "GET"
      | "POST"
      | "PUT"
      | "PATCH"
      | "DELETE";
    const parsed = splitTopLevelArgs(request[2]!);
    const url = literal(parsed[0] ?? "");
    if (url !== undefined) {
      const body = parseDataObject(parsed[1]);
      return {
        request: {
          method,
          url,
          ...(body !== undefined ? { body } : {}),
        },
      };
    }
  }

  const action =
    /^await\s+(page\..+?)\.(click|hover)\(\s*\);?$/.exec(line) ??
    /^await\s+(page\..+?)\.(fill)\((.+?)\);?$/.exec(line);
  if (!action) return undefined;

  const loc = locator(action[1]!);
  if (!loc) return undefined;
  const op = action[2]!;
  if (op === "click") return { click: loc };
  if (op === "hover") return { hover: loc };
  const value = literal(action[3] ?? "");
  if (value === undefined) return undefined;
  return { fill: { ...loc, value } };
}

function mapOutcome(line: string, idx: number): Outcome | undefined {
  const url = /^await\s+expect\(page\)\.toHaveURL\((.+?)\);?$/.exec(line);
  if (url) {
    const arg = url[1]!.trim();
    const matcher = regexLiteral(arg);
    if (matcher) {
      return outcome(idx, "url_matches", "page URL matches", {
        url: { matches: matcher },
      });
    }
    const value = literal(arg);
    if (value !== undefined) {
      return outcome(idx, "url_matches", "page URL matches", {
        url: value.startsWith("/") ? { endsWith: value } : { equals: value },
      });
    }
  }

  const visible = /^await\s+expect\((page\..+?)\)\.toBeVisible\(\s*\);?$/.exec(
    line,
  );
  if (visible) {
    const locText = locatorText(visible[1]!);
    if (locText) {
      return outcome(idx, "text_visible", "expected text is visible", {
        text: { contains: locText },
        region: "page",
      });
    }
    const loc = locator(visible[1]!);
    if (loc?.by === "selector") {
      return outcome(idx, "element_visible", "expected element is visible", {
        count: { selector: loc.selector, atLeast: 1 },
      });
    }
    if (loc?.by === "role") {
      return outcome(idx, "role_visible", "expected role is visible", {
        count: { role: loc.role, atLeast: 1 },
      });
    }
  }

  const contains =
    /^await\s+expect\((page\..+?)\)\.toContainText\((.+?)\);?$/.exec(line);
  if (contains) {
    const text = literal(contains[2]!);
    if (text !== undefined) {
      return outcome(idx, "text_contains", "expected text is present", {
        text: { contains: text },
        region: "page",
      });
    }
  }

  return undefined;
}

function outcome(
  idx: number,
  baseId: string,
  description: string,
  verify: Outcome["verify"],
): Outcome {
  return {
    id: idx === 0 ? baseId : `${baseId}_${idx + 1}`,
    description,
    verify,
  };
}

function locator(input: string): Locator | undefined {
  const testId = /^page\.getByTestId\((.+?)\)$/.exec(input);
  if (testId) {
    const id = literal(testId[1]!);
    if (id !== undefined) {
      return { by: "selector", selector: `[data-testid="${cssEscape(id)}"]` };
    }
  }

  const role = /^page\.getByRole\((.+?)\)$/.exec(input);
  if (role) {
    const args = splitTopLevelArgs(role[1]!);
    const roleName = literal(args[0] ?? "");
    if (roleName) {
      const name = objectStringProperty(args[1], "name");
      return { by: "role", role: roleName, ...(name ? { name } : {}) };
    }
  }

  const label = /^page\.getByLabel\((.+?)\)$/.exec(input);
  if (label) {
    const name = literal(label[1]!);
    if (name !== undefined) return { by: "label", name };
  }

  const text = /^page\.getByText\((.+?)\)$/.exec(input);
  if (text) {
    const value = literal(text[1]!);
    if (value !== undefined) return { by: "text", text: value };
  }

  const selector = /^page\.locator\((.+?)\)$/.exec(input);
  if (selector) {
    const value = literal(selector[1]!);
    if (value !== undefined) return { by: "selector", selector: value };
  }

  return undefined;
}

function locatorText(input: string): string | undefined {
  const text = /^page\.getByText\((.+?)\)$/.exec(input);
  if (text) return literal(text[1]!);
  return undefined;
}

function literal(input: string): string | undefined {
  const trimmed = input.trim();
  const m = /^(['"`])([\s\S]*)\1$/.exec(trimmed);
  return m?.[2];
}

function regexLiteral(input: string): string | undefined {
  const m = /^\/(.+)\/[a-z]*$/.exec(input.trim());
  return m?.[1];
}

function objectStringProperty(
  input: string | undefined,
  prop: string,
): string | undefined {
  if (!input) return undefined;
  const re = new RegExp(`${prop}\\s*:\\s*(['"\`])([\\s\\S]*?)\\1`);
  return re.exec(input)?.[2];
}

function parseDataObject(input: string | undefined): unknown {
  if (!input) return undefined;
  const data = /(?:^|[,{]\s*)data\s*:\s*({[\s\S]*?})\s*(?:,|})/.exec(
    input,
  )?.[1];
  if (!data) return undefined;
  try {
    return JSON.parse(
      data
        .replace(/([{,]\s*)([A-Za-z_$][\w$]*)\s*:/g, '$1"$2":')
        .replace(/'/g, '"'),
    );
  } catch {
    return undefined;
  }
}

function splitTopLevelArgs(input: string): string[] {
  const args: string[] = [];
  let current = "";
  let depth = 0;
  let quote: string | undefined;
  for (let i = 0; i < input.length; i++) {
    const ch = input[i]!;
    const prev = input[i - 1];
    if (quote) {
      current += ch;
      if (ch === quote && prev !== "\\") quote = undefined;
      continue;
    }
    if (ch === "'" || ch === '"' || ch === "`") {
      quote = ch;
      current += ch;
      continue;
    }
    if (ch === "{" || ch === "(" || ch === "[") depth++;
    if (ch === "}" || ch === ")" || ch === "]") depth--;
    if (ch === "," && depth === 0) {
      args.push(current.trim());
      current = "";
      continue;
    }
    current += ch;
  }
  if (current.trim()) args.push(current.trim());
  return args;
}

function cssEscape(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function slug(title: string): string {
  const s = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  const withLetter = /^[a-z]/.test(s) ? s : `imported_${s}`;
  return withLetter.slice(0, 80) || "imported_playwright";
}
