/**
 * Shared helpers emitted into `--project` as `lib/*.ts`. Single-file export
 * keeps the equivalent logic inlined so a piped `.spec.ts` stays standalone.
 */
type ExportLang = "ts" | "js";

export type PlaywrightLibModule =
  | "networkEvidence"
  | "hydration"
  | "clickUntil"
  | "verifier"
  | "splice"
  | "fixtures";

/**
 * `cairnSplice` / `cairnUnresolvedSplice` (+ the action binding shape) as
 * source lines. Splices render exactly like the runner's
 * resolveResponsePlaceholders / resolveEvalPlaceholders: objects and arrays
 * as JSON, missing names or paths as "".
 */
export function renderSpliceHelperLines(
  lang: ExportLang,
  opts: {
    splice: boolean;
    unresolved: boolean;
    bindings?: boolean;
    exported?: boolean;
  },
): string[] {
  const ts = lang === "ts";
  const exp = opts.exported ? "export " : "";
  const lines: string[] = [];
  if (opts.bindings && ts) {
    lines.push(
      `/** Values an exported action captured (request/eval/download \`assign:\`). */`,
      `${exp}interface CairnActionBindings {`,
      `  requests: Record<string, unknown>;`,
      `  evals: Record<string, unknown>;`,
      `  artifacts: Record<string, unknown>;`,
      `}`,
      ``,
    );
  }
  if (opts.splice) {
    lines.push(
      `/** Render a captured value like Cairntrace's runtime \${requests|evals|artifacts.…} splice. */`,
      `${exp}function cairnSplice(root${ts ? ": unknown" : ""}, path${
        ts ? ": string[]" : ""
      })${ts ? ": string" : ""} {`,
      `  let value = root;`,
      `  if (value === undefined) return "";`,
      `  for (const key of path) {`,
      `    if (value !== null && typeof value === "object" && key in value) {`,
      `      value = (value${ts ? " as Record<string, unknown>" : ""})[key];`,
      `    } else {`,
      `      return "";`,
      `    }`,
      `  }`,
      `  if (value === undefined || value === null) return "";`,
      `  return typeof value === "object" ? JSON.stringify(value) : String(value);`,
      `}`,
      ``,
    );
  }
  if (opts.unresolved) {
    lines.push(
      `/** A splice whose producing step is not available in this scope; the test is test.fixme. */`,
      `${exp}function cairnUnresolvedSplice(ref${ts ? ": string" : ""})${
        ts ? ": never" : ""
      } {`,
      `  throw new Error(`,
      `    "Cairntrace export could not bind the runtime splice " + ref +`,
      `      " (its producing step was not exported or runs in another scope); keep this flow in cairn run.",`,
      `  );`,
      `}`,
      ``,
    );
  }
  return lines;
}

export function renderSpliceRuntime(lang: ExportLang): string {
  return [
    `// Generated by \`cairn export playwright --project\`.`,
    `// Runtime splices for \${requests.<name>…} / \${evals.<name>…} / \${artifacts.<name>…}.`,
    ``,
    ...renderSpliceHelperLines(lang, {
      splice: true,
      unresolved: true,
      bindings: true,
      exported: true,
    }),
  ].join("\n");
}

export function renderFixturesRuntime(lang: ExportLang): string {
  const ts = lang === "ts";
  return [
    `// Generated by \`cairn export playwright --project\`.`,
    `// Upload fixtures are copied into <export>/fixtures/ so the suite is relocatable.`,
    `import { fileURLToPath } from "node:url";`,
    ``,
    `export function cairnFixturePath(name${ts ? ": string" : ""})${
      ts ? ": string" : ""
    } {`,
    `  return fileURLToPath(new URL("../fixtures/" + encodeURIComponent(name), import.meta.url));`,
    `}`,
    ``,
  ].join("\n");
}

/**
 * `lib/projectRoot` — resolves the Cairntrace SOURCE project (precondition
 * cwd, node verifier specDir) relative to the export root, never as a baked
 * absolute path. `relFromExportRoot` is computed from real paths at export
 * time; CAIRN_PROJECT_ROOT overrides it after a relocation. cairnProjectRoot()
 * validates existence and fails fast with guidance instead of letting a
 * precondition spawn in a missing cwd (`spawn /bin/bash ENOENT`).
 */
export function renderProjectRootRuntime(
  lang: ExportLang,
  relFromExportRoot: string | undefined,
): string {
  const ts = lang === "ts";
  const base =
    relFromExportRoot === undefined
      ? `process.cwd()`
      : `resolve(fileURLToPath(new URL("..", import.meta.url)), ${JSON.stringify(
          relFromExportRoot === "" ? "." : relFromExportRoot,
        )})`;
  return [
    `// Generated by \`cairn export playwright --project\`.`,
    `// Resolves the Cairntrace source project relative to this export's root.`,
    `// Override with CAIRN_PROJECT_ROOT when the export is relocated.`,
    `import { existsSync } from "node:fs";`,
    `import { join, resolve } from "node:path";`,
    ...(relFromExportRoot === undefined
      ? []
      : [`import { fileURLToPath } from "node:url";`]),
    ``,
    `/** Candidate path inside the source project (not validated). */`,
    `export function cairnProjectPath(...segments${ts ? ": string[]" : ""})${
      ts ? ": string" : ""
    } {`,
    `  const override = process.env.CAIRN_PROJECT_ROOT;`,
    `  const root = override ? resolve(override) : ${base};`,
    `  return join(root, ...segments);`,
    `}`,
    ``,
    `/** Validated source project root; throws with guidance when it is missing. */`,
    `export function cairnProjectRoot()${ts ? ": string" : ""} {`,
    `  const root = cairnProjectPath();`,
    `  if (!existsSync(root)) {`,
    `    throw new Error(`,
    `      "Cairntrace project root not found at " + root + ". " +`,
    `        (process.env.CAIRN_PROJECT_ROOT`,
    `          ? "CAIRN_PROJECT_ROOT points at a missing directory. "`,
    `          : "This export was moved away from its source project. ") +`,
    `        "Set CAIRN_PROJECT_ROOT to the directory that holds the Cairntrace specs before running tests with preconditions.",`,
    `    );`,
    `  }`,
    `  return root;`,
    `}`,
    ``,
  ].join("\n");
}

export function playwrightLibRelPath(
  name: PlaywrightLibModule,
  lang: ExportLang,
): string {
  return `lib/${name}${lang === "js" ? ".js" : ".ts"}`;
}

export function renderHydrationRuntime(lang: ExportLang): string {
  const ts = lang === "ts";
  const lines = [
    `// Generated by \`cairn export playwright --project\`.`,
    `// Fill/type retry when a hydration cycle wipes the authored value.`,
    `import { expect${
      ts ? ", type Locator, type Page" : ""
    } } from "@playwright/test";`,
    ``,
    `export async function verifiedFill(page${ts ? ": Page" : ""}, target${
      ts ? ": Locator" : ""
    }, value${ts ? ": string" : ""})${ts ? ": Promise<void>" : ""} {`,
    `  for (let fillAttempt = 0; ; fillAttempt++) {`,
    `    await target.fill(value);`,
    `    await page.waitForTimeout(500);`,
    `    try {`,
    `      await expect(target).toHaveValue(value, { timeout: 500 });`,
    `      break;`,
    `    } catch (err) {`,
    `      if (fillAttempt >= 3) throw new Error("hydration wiped value after 4 attempts", { cause: err });`,
    `    }`,
    `  }`,
    `}`,
    ``,
    `export async function verifiedType(page${ts ? ": Page" : ""}, target${
      ts ? ": Locator" : ""
    }, value${ts ? ": string" : ""}, typeOptions${
      ts ? "?: { delay?: number }" : ""
    })${ts ? ": Promise<void>" : ""} {`,
    `  for (let fillAttempt = 0; ; fillAttempt++) {`,
    `    if (fillAttempt > 0) await target.fill("");`,
    `    await target.pressSequentially(value, typeOptions);`,
    `    await page.waitForTimeout(500);`,
    `    try {`,
    `      await expect(target).toHaveValue(value, { timeout: 500 });`,
    `      break;`,
    `    } catch (err) {`,
    `      if (fillAttempt >= 3) throw new Error("hydration wiped value after 4 attempts", { cause: err });`,
    `    }`,
    `  }`,
    `}`,
    ``,
  ];
  return lines.join("\n");
}

export function renderClickUntilRuntime(lang: ExportLang): string {
  const ts = lang === "ts";
  const lines = [
    `// Generated by \`cairn export playwright --project\`.`,
    `// Bounded click retries matching Cairntrace click.until (4 attempts).`,
    `import { expect${
      ts ? ", type Locator, type Page" : ""
    } } from "@playwright/test";`,
    ``,
    ...(ts
      ? [
          `export interface ClickUntilOptions {`,
          `  timeoutMs: number;`,
          `  settleMs?: number;`,
          `  selectorGone?: string;`,
          `  selector?: string;`,
          `  urlEquals?: string;`,
          `  urlIncludes?: string;`,
          `  urlPattern?: string;`,
          `  text?: string;`,
          `  notText?: string;`,
          `}`,
          ``,
        ]
      : []),
    `function escapeRegExpLiteral(value${ts ? ": string" : ""})${
      ts ? ": string" : ""
    } {`,
    `  return value.replace(/[.*+?^\${}()|[\\]\\\\]/g, "\\\\$&");`,
    `}`,
    ``,
    `export async function clickUntil(page${ts ? ": Page" : ""}, clickTarget${
      ts ? ": Locator" : ""
    }, options${ts ? ": ClickUntilOptions" : ""})${
      ts ? ": Promise<void>" : ""
    } {`,
    `  const clickUntilDeadline = Date.now() + options.timeoutMs;`,
    `  for (let clickAttempt = 0; ; clickAttempt++) {`,
    `    await clickTarget.click();`,
    `    if (options.settleMs !== undefined && options.settleMs > 0) {`,
    `      await page.waitForLoadState("networkidle", { timeout: options.settleMs });`,
    `    }`,
    `    const clickUntilRemaining = Math.max(1, clickUntilDeadline - Date.now());`,
    `    const clickUntilAttemptTimeout = clickAttempt >= 3 ? clickUntilRemaining : Math.min(clickUntilRemaining, 250 * (2 ** clickAttempt));`,
    `    try {`,
    `      if (options.selectorGone !== undefined) {`,
    `        await expect(page.locator(options.selectorGone)).toHaveCount(0, { timeout: clickUntilAttemptTimeout });`,
    `      } else if (options.selector !== undefined) {`,
    `        await expect(page.locator(options.selector)).not.toHaveCount(0, { timeout: clickUntilAttemptTimeout });`,
    `      } else if (options.urlEquals !== undefined) {`,
    `        await expect(page).toHaveURL(options.urlEquals, { timeout: clickUntilAttemptTimeout });`,
    `      } else if (options.urlIncludes !== undefined) {`,
    `        await expect(page).toHaveURL(new RegExp(escapeRegExpLiteral(options.urlIncludes)), { timeout: clickUntilAttemptTimeout });`,
    `      } else if (options.urlPattern !== undefined) {`,
    `        await expect(page).toHaveURL(new RegExp(options.urlPattern), { timeout: clickUntilAttemptTimeout });`,
    `      } else if (options.text !== undefined) {`,
    `        await expect(page.locator("body")).toContainText(options.text, { ignoreCase: true, useInnerText: true, timeout: clickUntilAttemptTimeout });`,
    `      } else if (options.notText !== undefined) {`,
    `        await expect(page.locator("body")).not.toContainText(options.notText, { ignoreCase: true, useInnerText: true, timeout: clickUntilAttemptTimeout });`,
    `      } else {`,
    `        throw new Error("click.until is missing a condition");`,
    `      }`,
    `      break;`,
    `    } catch (err) {`,
    `      if (clickAttempt >= 3 || Date.now() >= clickUntilDeadline) {`,
    `        throw new Error("click.until condition was not satisfied after 4 attempts", { cause: err });`,
    `      }`,
    `    }`,
    `  }`,
    `}`,
    ``,
  ];
  return lines.join("\n");
}

export function renderVerifierRuntime(lang: ExportLang): string {
  const ts = lang === "ts";
  const lines = [
    `// Generated by \`cairn export playwright --project\`.`,
    `// ESM/CJS interop for node file verifiers (Playwright transpiles TS to CJS).`,
    ``,
    ...(ts
      ? [
          `export interface CairnVerifierContext {`,
          `  fixtures: Record<string, unknown>;`,
          `  artifacts: Record<string, unknown>;`,
          `  vars: Record<string, unknown>;`,
          `  runDir: string;`,
          `  specDir: string;`,
          `}`,
          ``,
          `export type CairnVerifier = (`,
          `  ctx: CairnVerifierContext,`,
          `) => Promise<{ ok?: boolean; evidence?: unknown }>;`,
          ``,
        ]
      : []),
    `export async function loadCairnVerifier(importedVerifier${
      ts ? ": unknown" : ""
    })${ts ? ": Promise<CairnVerifier>" : ""} {`,
    `  const verifierNamespace = importedVerifier${
      ts ? " as { verify?: unknown; default?: unknown }" : ""
    };`,
    `  const verifierDefault = verifierNamespace.default;`,
    `  const verifierDefaultNamespace = verifierDefault && typeof verifierDefault === "object"`,
    `    ? verifierDefault${
      ts ? " as { verify?: unknown; default?: unknown }" : ""
    }`,
    `    : undefined;`,
    `  const verify =`,
    `    verifierNamespace.verify ??`,
    `    (typeof verifierDefault === "function"`,
    `      ? verifierDefault`,
    `      : (verifierDefaultNamespace?.verify ?? verifierDefaultNamespace?.default));`,
    `  if (typeof verify !== "function") {`,
    `    throw new Error("verifier module must export a verify() function");`,
    `  }`,
    `  return verify${ts ? " as CairnVerifier" : ""};`,
    `}`,
    ``,
  ];
  return lines.join("\n");
}
