import type {
  CountVerifier,
  NetworkVerifier,
  NoFailedRequestsVerifier,
  TextMatcher,
  UrlMatcher,
  Verifier,
} from "../schema/verifier.v1";
import {
  isConsoleVerifier,
  isCountVerifier,
  isNetworkVerifier,
  isNoFailedRequestsVerifier,
  isNotTextVerifier,
  isScriptVerifier,
  isTextVerifier,
  isUrlVerifier,
} from "../schema/verifier.v1";
import type { Locator, Outcome, Spec, Step } from "../schema/spec.v1";

export interface ExportPlaywrightOptions {
  /** Path to the source spec; included in the generated file's header comment. */
  sourcePath?: string;
  /** Override the test title. Defaults to spec.name. */
  testTitle?: string;
}

/**
 * Generate a @playwright/test source file from a Cairntrace spec.
 *
 * Steps map to Playwright actions; outcomes map to expect() assertions.
 * Listener-based outcomes (network / noFailedRequests / console) install
 * collectors at the top of the test before any actions, then assert at the end.
 *
 * Output is meant to live in a separate Playwright project; this function
 * doesn't write files — the CLI does. Spec must have `use:` already expanded
 * (run `parseSpec` first and pass `result.resolved`).
 */
export function exportPlaywright(
  spec: Spec,
  opts: ExportPlaywrightOptions = {},
): string {
  const title = opts.testTitle ?? spec.name;
  const steps = spec.steps ?? [];

  // Figure out which listener-based collectors we need.
  const needsNetwork = spec.outcomes.some(
    (o) => isNetworkVerifier(o.verify) || isNoFailedRequestsVerifier(o.verify),
  );
  const needsConsole = spec.outcomes.some((o) => isConsoleVerifier(o.verify));

  const lines: string[] = [];

  /* ----- header ----- */
  lines.push(
    `// Generated by Cairntrace \`cairn export playwright\`. Edit at your own risk —`,
    `// re-running export will overwrite. Source: ${opts.sourcePath ?? "<unknown>"}`,
    `// Intent: ${oneLine(spec.intent)}`,
    "",
    `import { expect, test } from "@playwright/test";`,
    "",
    `test(${JSON.stringify(title)}, async ({ page }) => {`,
  );

  /* ----- collectors ----- */
  if (needsNetwork) {
    lines.push(
      `  const requests: Array<{ url: string; method: string; status?: number }> = [];`,
      `  page.on("response", (r) => requests.push({ url: r.url(), method: r.request().method(), status: r.status() }));`,
      "",
    );
  }
  if (needsConsole) {
    lines.push(
      `  const consoleErrors: string[] = [];`,
      `  page.on("console", (msg) => { if (msg.type() === "error") consoleErrors.push(msg.text()); });`,
      `  page.on("pageerror", (e) => consoleErrors.push(e.message));`,
      "",
    );
  }

  /* ----- steps ----- */
  if (steps.length > 0) {
    lines.push(`  // --- steps ---`);
    for (const step of steps) {
      lines.push(...renderStep(step).map((l) => `  ${l}`));
    }
    lines.push("");
  }

  /* ----- outcomes ----- */
  lines.push(`  // --- outcomes (the contract) ---`);
  for (const outcome of spec.outcomes) {
    lines.push(`  // ${outcome.id}: ${oneLine(outcome.description)}`);
    lines.push(...renderOutcome(outcome).map((l) => `  ${l}`));
    lines.push("");
  }

  lines.push(`});`);
  lines.push("");

  return lines.join("\n");
}

/* ----- step rendering ----- */

function renderStep(step: Step): string[] {
  const idComment = step.id ? `// step: ${step.id}` : "";
  const whenWrap = "when" in step && step.when ? step.when : undefined;
  const body = renderStepBody(step);
  const withComment = idComment ? [idComment, ...body] : body;
  if (!whenWrap) return withComment;
  // Wrap in an if-block for the when predicate. We comment the predicate since
  // a perfect translation would require duplicating the conditions DSL here.
  return [
    `// when: ${whenWrap} — Cairntrace evaluates this before the step; for parity`,
    `//   you'd need: ${renderWhenComment(whenWrap)}`,
    ...withComment,
  ];
}

function renderStepBody(step: Step): string[] {
  if ("open" in step) {
    return [`await page.goto(${JSON.stringify(step.open)});`];
  }
  if ("click" in step) {
    return [`await ${locator(step.click)}.click();`];
  }
  if ("hover" in step) {
    return [`await ${locator(step.hover)}.hover();`];
  }
  if ("fill" in step) {
    const { value, ...loc } = step.fill;
    return [`await ${locator(loc as Locator)}.fill(${JSON.stringify(value)});`];
  }
  if ("upload" in step) {
    const { path, ...loc } = step.upload;
    return [
      `await ${locator(loc as Locator)}.setInputFiles(${JSON.stringify(path)});`,
    ];
  }
  if ("download" in step) {
    const { saveAs, assign: _assign, timeoutMs, ...loc } = step.download;
    const timeout = timeoutMs ?? 30_000;
    return [
      `const download = await Promise.all([`,
      `  page.waitForEvent("download", { timeout: ${timeout} }),`,
      `  ${locator(loc as Locator)}.click(),`,
      `]).then(([download]) => download);`,
      `await download.saveAs(${JSON.stringify(saveAs)});`,
    ];
  }
  if ("transform" in step) {
    return [
      `// transform step skipped — Cairntrace runs ${JSON.stringify(step.transform.file)} in Node`,
    ];
  }
  if ("wait" in step) {
    const w = step.wait;
    const timeout = w.timeoutMs ?? 30_000;
    if ("text" in w) {
      return [
        `await page.waitForFunction(`,
        `  ${JSON.stringify(`document.body.innerText.includes(${JSON.stringify(w.text)})`)},`,
        `  undefined,`,
        `  { timeout: ${timeout} },`,
        `);`,
      ];
    }
    if ("notText" in w) {
      return [
        `await page.waitForFunction(`,
        `  ${JSON.stringify(`!document.body.innerText.includes(${JSON.stringify(w.notText)})`)},`,
        `  undefined,`,
        `  { timeout: ${timeout} },`,
        `);`,
      ];
    }
    return [
      `await page.waitForLoadState(${JSON.stringify(w.load)}, { timeout: ${timeout} });`,
    ];
  }
  if ("press" in step) {
    return [`await page.keyboard.press(${JSON.stringify(step.press)});`];
  }
  if ("scroll" in step) {
    if ("to" in step.scroll) {
      return [`await ${locator(step.scroll.to)}.scrollIntoViewIfNeeded();`];
    }
    const px = step.scroll.px ?? 400;
    const { direction } = step.scroll;
    const dx = direction === "left" ? -px : direction === "right" ? px : 0;
    const dy = direction === "up" ? -px : direction === "down" ? px : 0;
    return [`await page.mouse.wheel(${dx}, ${dy});`];
  }
  if ("snapshot" in step) {
    return [
      `// snapshot step skipped — Playwright traces cover this via context.tracing`,
    ];
  }
  if ("use" in step) {
    return [
      `// use: ${step.use} — expand imports via \`parseSpec\` before exporting`,
    ];
  }
  return [`// unhandled step: ${JSON.stringify(step)}`];
}

function locator(loc: Locator): string {
  const nth = "nth" in loc && loc.nth !== undefined ? `.nth(${loc.nth})` : "";
  switch (loc.by) {
    case "role": {
      const opts: string[] = [];
      if (loc.name) opts.push(`name: ${JSON.stringify(loc.name)}`);
      if (loc.exact) opts.push("exact: true");
      return `page.getByRole(${JSON.stringify(loc.role)}${
        opts.length > 0 ? `, { ${opts.join(", ")} }` : ""
      })${nth}`;
    }
    case "label":
      return `page.getByLabel(${JSON.stringify(loc.name)}${
        loc.exact ? ", { exact: true }" : ""
      })${nth}`;
    case "text":
      return `page.getByText(${JSON.stringify(loc.text)}${
        loc.exact ? ", { exact: true }" : ""
      })${nth}`;
    case "selector":
      return `page.locator(${JSON.stringify(loc.selector)})`;
  }
}

function renderWhenComment(when: string): string {
  const colon = when.indexOf(":");
  if (colon < 0) return when;
  const kind = when.slice(0, colon);
  const arg = when.slice(colon + 1);
  switch (kind) {
    case "urlContains":
      return `if (page.url().includes(${JSON.stringify(arg)})) { ... }`;
    case "urlNotContains":
      return `if (!page.url().includes(${JSON.stringify(arg)})) { ... }`;
    case "urlMatches":
      return `if (new RegExp(${JSON.stringify(arg)}).test(page.url())) { ... }`;
    case "text":
      return `if ((await page.locator("body").innerText()).includes(${JSON.stringify(arg)})) { ... }`;
    case "notText":
      return `if (!(await page.locator("body").innerText()).includes(${JSON.stringify(arg)})) { ... }`;
    default:
      return when;
  }
}

/* ----- outcome rendering ----- */

function renderOutcome(outcome: Outcome): string[] {
  const v = outcome.verify;
  if (isTextVerifier(v)) return renderTextOutcome(v.text, v.region, false);
  if (isNotTextVerifier(v)) return renderTextOutcome(v.notText, v.region, true);
  if (isUrlVerifier(v)) return renderUrlOutcome(v.url);
  if (isCountVerifier(v)) return renderCountOutcome(v);
  if (isNetworkVerifier(v)) return renderNetworkOutcome(v);
  if (isNoFailedRequestsVerifier(v)) return renderNoFailedRequestsOutcome(v);
  if (isConsoleVerifier(v))
    return [
      `expect(consoleErrors.length).toBeLessThanOrEqual(${v.console.errorsMax});`,
    ];
  if (isScriptVerifier(v)) return renderScriptOutcome(v);
  return [`// unhandled verifier kind for ${JSON.stringify(Object.keys(v))}`];
}

function renderTextOutcome(
  m: TextMatcher,
  region: string,
  negated: boolean,
): string[] {
  const target =
    region === "page"
      ? `page.locator("body")`
      : `page.locator(${JSON.stringify(region)})`;
  const not = negated ? ".not" : "";
  if (m.equals !== undefined) {
    return [
      `await expect(${target})${not}.toHaveText(${JSON.stringify(m.equals)});`,
    ];
  }
  if (m.contains !== undefined) {
    return [
      `await expect(${target})${not}.toContainText(${JSON.stringify(m.contains)});`,
    ];
  }
  if (m.matches !== undefined) {
    return [
      `await expect(${target})${not}.toHaveText(new RegExp(${JSON.stringify(m.matches)}));`,
    ];
  }
  return [`// invalid text matcher`];
}

function renderUrlOutcome(m: UrlMatcher): string[] {
  if (m.equals !== undefined) {
    return [`await expect(page).toHaveURL(${JSON.stringify(m.equals)});`];
  }
  if (m.startsWith !== undefined) {
    return [
      `await expect(page).toHaveURL(new RegExp(${JSON.stringify("^" + escapeRegex(m.startsWith))}));`,
    ];
  }
  if (m.endsWith !== undefined) {
    return [
      `await expect(page).toHaveURL(new RegExp(${JSON.stringify(escapeRegex(m.endsWith) + "$")}));`,
    ];
  }
  if (m.matches !== undefined) {
    return [
      `await expect(page).toHaveURL(new RegExp(${JSON.stringify(m.matches)}));`,
    ];
  }
  return [`// invalid url matcher`];
}

function renderCountOutcome(v: CountVerifier): string[] {
  const c = v.count;
  let target: string;
  const region = c.in_region ? JSON.stringify(c.in_region) : undefined;
  const base = region ? `page.locator(${region})` : `page`;
  if (c.selector) {
    target = `${base}.locator(${JSON.stringify(c.selector)})`;
  } else if (c.role) {
    target = `${base}.getByRole(${JSON.stringify(c.role)})`;
  } else if (c.text) {
    target = `${base}.getByText(${JSON.stringify(c.text)})`;
  } else {
    return [`// count verifier requires role/selector/text`];
  }
  if (c.equals !== undefined) {
    return [`await expect(${target}).toHaveCount(${c.equals});`];
  }
  if (c.atLeast !== undefined) {
    return [
      `expect(await ${target}.count()).toBeGreaterThanOrEqual(${c.atLeast});`,
    ];
  }
  if (c.atMost !== undefined) {
    return [
      `expect(await ${target}.count()).toBeLessThanOrEqual(${c.atMost});`,
    ];
  }
  if (c.between !== undefined) {
    const [lo, hi] = c.between;
    return [
      `{`,
      `  const n = await ${target}.count();`,
      `  expect(n).toBeGreaterThanOrEqual(${lo});`,
      `  expect(n).toBeLessThanOrEqual(${hi});`,
      `}`,
    ];
  }
  return [`// invalid count matcher`];
}

function renderNetworkOutcome(v: NetworkVerifier): string[] {
  const n = v.network;
  const conds: string[] = [];
  if (n.method) conds.push(`r.method === ${JSON.stringify(n.method)}`);
  conds.push(`r.url.includes(${JSON.stringify(n.urlContains)})`);
  const s = n.status;
  if (s.equals !== undefined) conds.push(`r.status === ${s.equals}`);
  else if (s.below !== undefined) conds.push(`(r.status ?? 0) < ${s.below}`);
  else if (s.atLeast !== undefined)
    conds.push(`(r.status ?? 0) >= ${s.atLeast}`);
  else if (s.in !== undefined)
    conds.push(`[${s.in.join(", ")}].includes(r.status ?? -1)`);
  return [`expect(requests.some((r) => ${conds.join(" && ")})).toBe(true);`];
}

function renderNoFailedRequestsOutcome(v: NoFailedRequestsVerifier): string[] {
  const n = v.noFailedRequests;
  const conds = [`r.url.includes(${JSON.stringify(n.urlContains)})`];
  if (n.method) conds.push(`r.method === ${JSON.stringify(n.method)}`);
  return [
    `expect(requests.filter((r) => ${conds.join(" && ")} && (r.status ?? 0) >= 400)).toEqual([]);`,
  ];
}

function renderScriptOutcome(
  v: import("../schema/verifier.v1").ScriptVerifier,
): string[] {
  const fixtures = JSON.stringify(v.script.fixtures ?? {});
  if (v.script.file) {
    return [
      `// script.file ${JSON.stringify(v.script.file)} is not inlined by the exporter yet.`,
      `// Keep the Cairntrace spec as the source of truth or inline the script.run body before export.`,
    ];
  }
  return [
    `{`,
    `  const result = await page.evaluate(() => {`,
    `    const fixtures = ${fixtures};`,
    `    return (function(){`,
    ...(v.script.run ?? "").split("\n").map((l) => `      ${l}`),
    `    })();`,
    `  });`,
    `  expect(result.ok).toBe(true);`,
    `}`,
  ];
}

/* ----- helpers ----- */

function oneLine(s: string): string {
  return s.replaceAll(/\s+/g, " ").trim();
}

function escapeRegex(s: string): string {
  return s.replaceAll(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Used by tests + the CLI to know whether a verifier type is exportable. */
export function isExportable(v: Verifier): boolean {
  return (
    isTextVerifier(v) ||
    isNotTextVerifier(v) ||
    isUrlVerifier(v) ||
    isCountVerifier(v) ||
    isNetworkVerifier(v) ||
    isNoFailedRequestsVerifier(v) ||
    isConsoleVerifier(v) ||
    isScriptVerifier(v)
  );
}
