import type {
  CountVerifier,
  NetworkVerifier,
  NoFailedRequestsVerifier,
  TextMatcher,
  UrlMatcher,
  Verifier,
} from "../schema/verifier.v1";
import {
  isConsoleVerifier,
  isCountVerifier,
  isHttpJsonVerifier,
  isNetworkVerifier,
  isNoFailedRequestsVerifier,
  isNotTextVerifier,
  isScriptVerifier,
  isTextVerifier,
  isUrlVerifier,
  notTextVerifierRegion,
  textVerifierRegion,
} from "../schema/verifier.v1";
import type {
  BatchSubStep,
  Locator,
  Outcome,
  Spec,
  Step,
} from "../schema/spec.v1";
import { bodyTextContainsExpression } from "../textMatching";

export type ExportLang = "ts" | "js";

export interface ExportPlaywrightOptions {
  /** Path to the source spec; included in the generated file's header comment. */
  sourcePath?: string;
  /** Override the test title. Defaults to spec.name. */
  testTitle?: string;
  /** Emit TypeScript (default) or plain JavaScript. */
  lang?: ExportLang;
}

export interface ExportCoverageSkip {
  kind: "step" | "outcome" | "when";
  id?: string;
  reason: string;
}

export interface ExportCoverage {
  stepsTotal: number;
  stepsExported: number;
  outcomesTotal: number;
  outcomesExported: number;
  skips: ExportCoverageSkip[];
}

export interface ExportPlaywrightResult {
  source: string;
  lang: ExportLang;
  coverage: ExportCoverage;
}

/**
 * Generate a @playwright/test source file from a Cairntrace spec.
 *
 * Steps map to Playwright actions; outcomes map to expect() assertions.
 * Listener-based outcomes (network / noFailedRequests / console) install
 * collectors at the top of the test before any actions, then assert at the end.
 *
 * Output is meant to live in a separate Playwright project; this function
 * doesn't write files — the CLI does. Spec must have `use:` already expanded
 * (run `parseSpec` first and pass `result.resolved`).
 */
export function exportPlaywright(
  spec: Spec,
  opts: ExportPlaywrightOptions = {},
): ExportPlaywrightResult {
  const lang: ExportLang = opts.lang ?? "ts";
  const title = opts.testTitle ?? spec.name;
  const steps = spec.steps ?? [];
  const coverage: ExportCoverage = {
    stepsTotal: steps.length,
    stepsExported: 0,
    outcomesTotal: spec.outcomes.length,
    outcomesExported: 0,
    skips: [],
  };
  const ctx: EmitCtx = { lang, coverage };

  const needsNetwork = spec.outcomes.some(
    (o) => isNetworkVerifier(o.verify) || isNoFailedRequestsVerifier(o.verify),
  );
  const needsConsole = spec.outcomes.some((o) => isConsoleVerifier(o.verify));

  const lines: string[] = [];

  lines.push(
    `// Generated by Cairntrace \`cairn export playwright\`. Edit at your own risk —`,
    `// re-running export will overwrite. Source: ${opts.sourcePath ?? "<unknown>"}`,
    `// Intent: ${oneLine(spec.intent)}`,
    `// Lang: ${lang}`,
    "",
    `import { expect, test } from "@playwright/test";`,
    "",
    `test(${JSON.stringify(title)}, async ({ page }) => {`,
  );

  if (needsNetwork) {
    const typeAnn =
      lang === "ts"
        ? `: Array<{ url: string; method: string; status?: number }>`
        : "";
    lines.push(
      `  const requests${typeAnn} = [];`,
      `  page.on("response", (r) => requests.push({ url: r.url(), method: r.request().method(), status: r.status() }));`,
      "",
    );
  }
  if (needsConsole) {
    const typeAnn = lang === "ts" ? `: string[]` : "";
    lines.push(
      `  const consoleErrors${typeAnn} = [];`,
      `  page.on("console", (msg) => { if (msg.type() === "error") consoleErrors.push(msg.text()); });`,
      `  page.on("pageerror", (e) => consoleErrors.push(e.message));`,
      "",
    );
  }

  if (steps.length > 0) {
    lines.push(`  // --- steps ---`);
    for (const step of steps) {
      const rendered = renderStep(step, spec.settleMs, ctx);
      if (rendered.exported) coverage.stepsExported += 1;
      lines.push(...rendered.lines.map((l) => `  ${l}`));
    }
    lines.push("");
  }

  lines.push(`  // --- outcomes (the contract) ---`);
  for (const outcome of spec.outcomes) {
    lines.push(`  // ${outcome.id}: ${oneLine(outcome.description)}`);
    const rendered = renderOutcome(outcome, ctx);
    if (rendered.exported) coverage.outcomesExported += 1;
    lines.push(...rendered.lines.map((l) => `  ${l}`));
    lines.push("");
  }

  lines.push(`});`);
  lines.push("");

  return {
    source: lines.join("\n"),
    lang,
    coverage,
  };
}

/* ----- emit context ----- */

interface EmitCtx {
  lang: ExportLang;
  coverage: ExportCoverage;
}

interface Rendered {
  lines: string[];
  /** True when at least one executable Playwright line was produced. */
  exported: boolean;
}

function skip(
  ctx: EmitCtx,
  kind: ExportCoverageSkip["kind"],
  reason: string,
  id?: string,
): void {
  ctx.coverage.skips.push({ kind, id, reason });
}

/* ----- step rendering ----- */

function renderStep(
  step: Step,
  specSettleMs: number | undefined,
  ctx: EmitCtx,
): Rendered {
  const idComment = step.id ? `// step: ${oneLine(step.id)}` : "";
  const whenWrap = "when" in step && step.when ? step.when : undefined;
  const body = renderStepBody(step, specSettleMs, ctx);
  const withComment = idComment ? [idComment, ...body.lines] : body.lines;

  if (!whenWrap) return { lines: withComment, exported: body.exported };

  const wrapped = wrapWhen(whenWrap, withComment, ctx, step.id);
  return wrapped;
}

function wrapWhen(
  when: string,
  body: string[],
  ctx: EmitCtx,
  stepId?: string,
): Rendered {
  const colon = when.indexOf(":");
  if (colon < 0) {
    skip(ctx, "when", `unrecognized when predicate: ${when}`, stepId);
    return {
      lines: [
        `// when: ${oneLine(when)} — not translated; step always runs`,
        ...body,
      ],
      exported: body.length > 0,
    };
  }
  const kind = when.slice(0, colon);
  const arg = when.slice(colon + 1);
  let condition: string | undefined;
  switch (kind) {
    case "urlContains":
      condition = `page.url().includes(${JSON.stringify(arg)})`;
      break;
    case "urlNotContains":
      condition = `!page.url().includes(${JSON.stringify(arg)})`;
      break;
    case "urlMatches":
      condition = `new RegExp(${JSON.stringify(arg)}).test(page.url())`;
      break;
    case "text":
      condition = `await page.evaluate(() => ${bodyTextContainsExpression(arg, false)})`;
      break;
    case "notText":
      condition = `await page.evaluate(() => !(${bodyTextContainsExpression(arg, false)}))`;
      break;
    default:
      skip(ctx, "when", `unsupported when kind: ${kind}`, stepId);
      return {
        lines: [
          `// when: ${oneLine(when)} — not translated; step always runs`,
          ...body,
        ],
        exported: body.length > 0,
      };
  }
  return {
    lines: [
      `// when: ${oneLine(when)}`,
      `if (${condition}) {`,
      ...body.map((l) => `  ${l}`),
      `}`,
    ],
    exported: body.length > 0,
  };
}

function renderStepBody(
  step: Step,
  specSettleMs: number | undefined,
  ctx: EmitCtx,
): Rendered {
  if ("open" in step) {
    if (typeof step.open === "string") {
      return {
        lines: [`await page.goto(${JSON.stringify(step.open)});`],
        exported: true,
      };
    }
    const opts: string[] = [
      `waitUntil: ${JSON.stringify(step.open.waitUntil)}`,
    ];
    if (step.open.timeoutMs !== undefined) {
      opts.push(`timeout: ${step.open.timeoutMs}`);
    }
    return {
      lines: [
        `await page.goto(${JSON.stringify(step.open.path)}, { ${opts.join(", ")} });`,
      ],
      exported: true,
    };
  }
  if ("click" in step) {
    const settleMs = step.settleMs ?? specSettleMs;
    return {
      lines: [
        `await ${locator(step.click)}.click();`,
        ...(settleMs !== undefined && settleMs > 0
          ? [
              `await page.waitForLoadState("networkidle", { timeout: ${settleMs} });`,
            ]
          : []),
      ],
      exported: true,
    };
  }
  if ("hover" in step) {
    return {
      lines: [`await ${locator(step.hover)}.hover();`],
      exported: true,
    };
  }
  if ("fill" in step) {
    const { value, ...loc } = step.fill;
    return {
      lines: [
        `await ${locator(loc as Locator)}.fill(${JSON.stringify(value)});`,
      ],
      exported: true,
    };
  }
  if ("type" in step) {
    const { value, delayMs, ...loc } = step.type;
    const opts = delayMs !== undefined ? `, { delay: ${delayMs} }` : "";
    return {
      lines: [
        `await ${locator(loc as Locator)}.pressSequentially(${JSON.stringify(value)}${opts});`,
      ],
      exported: true,
    };
  }
  if ("select" in step) {
    const { value, label, ...loc } = step.select;
    const option =
      value !== undefined
        ? `{ value: ${JSON.stringify(value)} }`
        : `{ label: ${JSON.stringify(label)} }`;
    return {
      lines: [`await ${locator(loc as Locator)}.selectOption(${option});`],
      exported: true,
    };
  }
  if ("upload" in step) {
    const { path, ...loc } = step.upload;
    return {
      lines: [
        `await ${locator(loc as Locator)}.setInputFiles(${JSON.stringify(path)});`,
      ],
      exported: true,
    };
  }
  if ("download" in step) {
    const { saveAs, assign: _assign, timeoutMs, ...loc } = step.download;
    const timeout = timeoutMs ?? 30_000;
    return {
      lines: [
        `const download = await Promise.all([`,
        `  page.waitForEvent("download", { timeout: ${timeout} }),`,
        `  ${locator(loc as Locator)}.click(),`,
        `]).then(([download]) => download);`,
        `await download.saveAs(${JSON.stringify(saveAs)});`,
      ],
      exported: true,
    };
  }
  if ("transform" in step) {
    skip(
      ctx,
      "step",
      `transform step not exportable (${step.transform.file})`,
      step.id,
    );
    return {
      lines: [
        `// transform step skipped — Cairntrace runs ${JSON.stringify(step.transform.file)} in Node`,
      ],
      exported: false,
    };
  }
  if ("request" in step) {
    return renderRequestStep(step, ctx);
  }
  if ("eval" in step) {
    return renderEvalStep(step, ctx);
  }
  if ("batch" in step) {
    return renderBatchStep(step, specSettleMs, ctx);
  }
  if ("wait" in step) {
    const w = step.wait;
    const timeout = w.timeoutMs ?? 30_000;
    if ("text" in w) {
      return {
        lines: [
          `await page.waitForFunction(`,
          `  ${JSON.stringify(bodyTextContainsExpression(w.text, w.caseSensitive ?? false))},`,
          `  undefined,`,
          `  { timeout: ${timeout} },`,
          `);`,
        ],
        exported: true,
      };
    }
    if ("notText" in w) {
      const expression = bodyTextContainsExpression(
        w.notText,
        w.caseSensitive ?? false,
      );
      return {
        lines: [
          `await page.waitForFunction(`,
          `  ${JSON.stringify(`!(${expression})`)},`,
          `  undefined,`,
          `  { timeout: ${timeout} },`,
          `);`,
        ],
        exported: true,
      };
    }
    if ("selector" in w) {
      const opts = [`timeout: ${timeout}`];
      const state = w.state ?? "visible";
      opts.push(`state: ${JSON.stringify(state)}`);
      return {
        lines: [
          `await page.waitForSelector(${JSON.stringify(w.selector)}, { ${opts.join(", ")} });`,
        ],
        exported: true,
      };
    }
    return {
      lines: [
        `await page.waitForLoadState(${JSON.stringify(w.load)}, { timeout: ${timeout} });`,
      ],
      exported: true,
    };
  }
  if ("press" in step) {
    return {
      lines: [`await page.keyboard.press(${JSON.stringify(step.press)});`],
      exported: true,
    };
  }
  if ("scroll" in step) {
    if ("to" in step.scroll) {
      return {
        lines: [`await ${locator(step.scroll.to)}.scrollIntoViewIfNeeded();`],
        exported: true,
      };
    }
    const px = step.scroll.px ?? 400;
    const { direction } = step.scroll;
    const dx = direction === "left" ? -px : direction === "right" ? px : 0;
    const dy = direction === "up" ? -px : direction === "down" ? px : 0;
    return {
      lines: [`await page.mouse.wheel(${dx}, ${dy});`],
      exported: true,
    };
  }
  if ("snapshot" in step) {
    skip(ctx, "step", "snapshot step not exportable", step.id);
    return {
      lines: [
        `// snapshot step skipped — Playwright traces cover this via context.tracing`,
      ],
      exported: false,
    };
  }
  if ("monitor" in step) {
    skip(ctx, "step", "monitor step not exportable (external CLI)", step.id);
    return {
      lines: [
        `// monitor step skipped — no Playwright equivalent for the monitor CLI`,
      ],
      exported: false,
    };
  }
  if ("use" in step) {
    skip(
      ctx,
      "step",
      `use: ${step.use} not expanded — pass parseSpec().resolved`,
      step.id,
    );
    return {
      lines: [
        `// use: ${oneLine(step.use)} — expand imports via \`parseSpec\` before exporting`,
      ],
      exported: false,
    };
  }
  const unknownStep = step as { id?: string };
  skip(ctx, "step", `unhandled step shape`, unknownStep.id);
  return {
    lines: [`// unhandled step: ${JSON.stringify(step)}`],
    exported: false,
  };
}

function renderEvalStep(
  step: Extract<Step, { eval: unknown }>,
  ctx: EmitCtx,
): Rendered {
  const e = step.eval;
  if (e.file) {
    skip(ctx, "step", `eval.file not inlined (${e.file})`, step.id);
    return {
      lines: [
        `// eval.file ${JSON.stringify(e.file)} is not inlined by the exporter.`,
        `// Copy the file body into an eval.js step, or keep the Cairntrace spec as SoT.`,
      ],
      exported: false,
    };
  }
  const js = e.js ?? "";
  const argsJson = JSON.stringify(e.args ?? {});
  const assign = e.assign ? `const ${safeIdent(e.assign)} = ` : "";
  const lines = [
    `${assign}await page.evaluate(async (args) => {`,
    ...js.split("\n").map((l) => `  ${l}`),
    `}, ${argsJson});`,
  ];
  if (e.assign) {
    lines.push(
      `// Note: later steps that splice \${evals.${e.assign}…} are not rewritten — wire variables manually if needed.`,
    );
  }
  return { lines, exported: true };
}

function renderBatchStep(
  step: Extract<Step, { batch: unknown }>,
  specSettleMs: number | undefined,
  ctx: EmitCtx,
): Rendered {
  const lines: string[] = [
    `// batch: expanded sequentially — Playwright cannot preserve hover/focus atomicity like agent-browser batch`,
  ];
  let any = false;
  for (const sub of step.batch as BatchSubStep[]) {
    // Batch sub-steps are a restricted Step subset; cast through unknown.
    const asStep = sub as unknown as Step;
    const rendered = renderStepBody(asStep, specSettleMs, ctx);
    lines.push(...rendered.lines);
    if (rendered.exported) any = true;
  }
  return { lines, exported: any };
}

function renderRequestStep(
  step: Extract<Step, { request: unknown }>,
  _ctx: EmitCtx,
): Rendered {
  const r = step.request;
  const method = (r.method ?? "GET").toUpperCase();
  const timeout = r.timeoutMs ?? 30_000;
  const headers: Record<string, string> = { ...r.headers };
  if (
    r.body !== undefined &&
    typeof r.body !== "string" &&
    !Object.keys(headers).some((h) => h.toLowerCase() === "content-type")
  ) {
    headers["Content-Type"] = "application/json";
  }
  const opts: string[] = [
    `method: ${JSON.stringify(method)}`,
    `timeout: ${timeout}`,
  ];
  if (Object.keys(headers).length > 0) {
    opts.push(`headers: ${JSON.stringify(headers)}`);
  }
  if (r.body !== undefined) {
    opts.push(`data: ${JSON.stringify(r.body)}`);
  }
  const varName = r.assign ? safeIdent(r.assign) : "_res";
  const lines = [
    `// request step (${r.assign ?? "unnamed"}) — page.request shares browser context cookies`,
    `const ${varName} = await page.request.fetch(${JSON.stringify(r.url)}, { ${opts.join(", ")} });`,
  ];
  if (r.expectStatus !== undefined) {
    if (Array.isArray(r.expectStatus)) {
      lines.push(
        `expect([${r.expectStatus.join(", ")}]).toContain(${varName}.status());`,
      );
    } else {
      lines.push(`expect(${varName}.status()).toBe(${r.expectStatus});`);
    }
  }
  if (r.assign) {
    lines.push(
      `// Response body: await ${varName}.json() or .text() — \${requests.${r.assign}.*} placeholders are not auto-rewritten below.`,
    );
  }
  return { lines, exported: true };
}

function locator(loc: Locator): string {
  const nth = "nth" in loc && loc.nth !== undefined ? `.nth(${loc.nth})` : "";
  switch (loc.by) {
    case "role": {
      const opts: string[] = [];
      if (loc.name) opts.push(`name: ${JSON.stringify(loc.name)}`);
      if (loc.exact) opts.push("exact: true");
      return `page.getByRole(${JSON.stringify(loc.role)}${
        opts.length > 0 ? `, { ${opts.join(", ")} }` : ""
      })${nth}`;
    }
    case "label":
      return `page.getByLabel(${JSON.stringify(loc.name)}${
        loc.exact ? ", { exact: true }" : ""
      })${nth}`;
    case "text":
      return `page.getByText(${JSON.stringify(loc.text)}${
        loc.exact ? ", { exact: true }" : ""
      })${nth}`;
    case "selector":
      return `page.locator(${JSON.stringify(loc.selector)})`;
  }
}

/* ----- outcome rendering ----- */

function renderOutcome(outcome: Outcome, ctx: EmitCtx): Rendered {
  const v = outcome.verify;
  if (isTextVerifier(v))
    return {
      lines: renderTextOutcome(v.text, textVerifierRegion(v), false),
      exported: true,
    };
  if (isNotTextVerifier(v))
    return {
      lines: renderTextOutcome(v.notText, notTextVerifierRegion(v), true),
      exported: true,
    };
  if (isUrlVerifier(v))
    return { lines: renderUrlOutcome(v.url), exported: true };
  if (isCountVerifier(v))
    return { lines: renderCountOutcome(v), exported: true };
  if (isNetworkVerifier(v))
    return { lines: renderNetworkOutcome(v), exported: true };
  if (isNoFailedRequestsVerifier(v))
    return { lines: renderNoFailedRequestsOutcome(v), exported: true };
  if (isConsoleVerifier(v))
    return {
      lines: [
        `expect(consoleErrors.length).toBeLessThanOrEqual(${v.console.errorsMax});`,
      ],
      exported: true,
    };
  if (isScriptVerifier(v)) return renderScriptOutcome(v, outcome.id, ctx);
  if (isHttpJsonVerifier(v)) return renderHttpJsonOutcome(v, outcome.id, ctx);
  skip(
    ctx,
    "outcome",
    `unhandled verifier kind: ${Object.keys(v).join(",")}`,
    outcome.id,
  );
  return {
    lines: [`// unhandled verifier kind for ${JSON.stringify(Object.keys(v))}`],
    exported: false,
  };
}

function renderTextOutcome(
  m: TextMatcher,
  region: string,
  negated: boolean,
): string[] {
  const target =
    region === "page"
      ? `page.locator("body")`
      : `page.locator(${JSON.stringify(region)})`;
  const not = negated ? ".not" : "";
  if (m.equals !== undefined) {
    return [
      `await expect(${target})${not}.toHaveText(${JSON.stringify(m.equals)}, ${renderTextAssertionOptions(m.caseSensitive ?? false)});`,
    ];
  }
  if (m.contains !== undefined) {
    return [
      `await expect(${target})${not}.toContainText(${JSON.stringify(m.contains)}, ${renderTextAssertionOptions(m.caseSensitive ?? false)});`,
    ];
  }
  if (m.matches !== undefined) {
    return [
      `await expect(${target})${not}.toHaveText(new RegExp(${JSON.stringify(m.matches)}));`,
    ];
  }
  return [`// invalid text matcher`];
}

function renderTextAssertionOptions(caseSensitive: boolean): string {
  return `{ ignoreCase: ${!caseSensitive}, useInnerText: true }`;
}

function renderUrlOutcome(m: UrlMatcher): string[] {
  if (m.equals !== undefined) {
    return [`await expect(page).toHaveURL(${JSON.stringify(m.equals)});`];
  }
  if (m.startsWith !== undefined) {
    return [
      `await expect(page).toHaveURL(new RegExp(${JSON.stringify("^" + escapeRegex(m.startsWith))}));`,
    ];
  }
  if (m.endsWith !== undefined) {
    return [
      `await expect(page).toHaveURL(new RegExp(${JSON.stringify(escapeRegex(m.endsWith) + "$")}));`,
    ];
  }
  if (m.matches !== undefined) {
    return [
      `await expect(page).toHaveURL(new RegExp(${JSON.stringify(m.matches)}));`,
    ];
  }
  return [`// invalid url matcher`];
}

function renderCountOutcome(v: CountVerifier): string[] {
  const c = v.count;
  let target: string;
  const region = c.in_region ? JSON.stringify(c.in_region) : undefined;
  const base = region ? `page.locator(${region})` : `page`;
  if (c.selector) {
    target = `${base}.locator(${JSON.stringify(c.selector)})`;
  } else if (c.role) {
    target = `${base}.getByRole(${JSON.stringify(c.role)})`;
  } else {
    return [`// count verifier requires role/selector`];
  }
  if (c.equals !== undefined) {
    return [`await expect(${target}).toHaveCount(${c.equals});`];
  }
  if (c.atLeast !== undefined) {
    return [
      `expect(await ${target}.count()).toBeGreaterThanOrEqual(${c.atLeast});`,
    ];
  }
  if (c.atMost !== undefined) {
    return [
      `expect(await ${target}.count()).toBeLessThanOrEqual(${c.atMost});`,
    ];
  }
  if (c.between !== undefined) {
    const [lo, hi] = c.between;
    return [
      `{`,
      `  const n = await ${target}.count();`,
      `  expect(n).toBeGreaterThanOrEqual(${lo});`,
      `  expect(n).toBeLessThanOrEqual(${hi});`,
      `}`,
    ];
  }
  return [`// invalid count matcher`];
}

function renderNetworkOutcome(v: NetworkVerifier): string[] {
  const n = v.network;
  const conds: string[] = [];
  if (n.method) conds.push(`r.method === ${JSON.stringify(n.method)}`);
  conds.push(`r.url.includes(${JSON.stringify(n.urlContains)})`);
  const s = n.status;
  if (s.equals !== undefined) conds.push(`r.status === ${s.equals}`);
  else if (s.below !== undefined) conds.push(`(r.status ?? 0) < ${s.below}`);
  else if (s.atLeast !== undefined)
    conds.push(`(r.status ?? 0) >= ${s.atLeast}`);
  else if (s.in !== undefined)
    conds.push(`[${s.in.join(", ")}].includes(r.status ?? -1)`);
  return [`expect(requests.some((r) => ${conds.join(" && ")})).toBe(true);`];
}

function renderNoFailedRequestsOutcome(v: NoFailedRequestsVerifier): string[] {
  const n = v.noFailedRequests;
  const conds = [`r.url.includes(${JSON.stringify(n.urlContains)})`];
  if (n.method) conds.push(`r.method === ${JSON.stringify(n.method)}`);
  return [
    `expect(requests.filter((r) => ${conds.join(" && ")} && (r.status ?? 0) >= 400)).toEqual([]);`,
  ];
}

function renderScriptOutcome(
  v: import("../schema/verifier.v1").ScriptVerifier,
  outcomeId: string,
  ctx: EmitCtx,
): Rendered {
  if (v.script.runtime === "node" || v.script.file) {
    const reason = v.script.file
      ? `script.file ${v.script.file} not inlined`
      : "script.runtime node not exportable to browser test";
    skip(ctx, "outcome", reason, outcomeId);
    return {
      lines: [`// ${reason}. Keep the Cairntrace spec as the source of truth.`],
      exported: false,
    };
  }
  const fixtures = JSON.stringify(v.script.fixtures ?? {});
  return {
    lines: [
      `{`,
      `  const result = await page.evaluate(() => {`,
      `    const fixtures = ${fixtures};`,
      `    return (function(){`,
      ...(v.script.run ?? "").split("\n").map((l) => `      ${l}`),
      `    })();`,
      `  });`,
      `  expect(result.ok).toBe(true);`,
      `}`,
    ],
    exported: true,
  };
}

function renderHttpJsonOutcome(
  v: import("../schema/verifier.v1").HttpJsonVerifier,
  outcomeId: string,
  ctx: EmitCtx,
): Rendered {
  const h = v.httpJson;
  // Best-effort GET + simple equals/contains on a dotted jsonPath.
  const pathExpr = `String(${JSON.stringify(h.jsonPath ?? "$")}).replace(/^\\$\\.?/, "").split(".").filter(Boolean).reduce((o, k) => (o == null ? o : o[k]), body)`;
  const lines = [
    `{`,
    `  const res = await page.request.get(${JSON.stringify(h.url)});`,
    `  expect(res.ok()).toBeTruthy();`,
    `  const body = await res.json();`,
    `  const val = ${pathExpr};`,
  ];
  if (h.equals !== undefined) {
    lines.push(`  expect(val).toEqual(${JSON.stringify(h.equals)});`);
  } else if (h.contains !== undefined) {
    lines.push(
      `  expect(String(val)).toContain(${JSON.stringify(h.contains)});`,
    );
  } else if (h.exists !== undefined) {
    lines.push(
      h.exists
        ? `  expect(val).not.toBeUndefined();`
        : `  expect(val).toBeUndefined();`,
    );
  } else {
    skip(
      ctx,
      "outcome",
      "httpJson matcher (matches/atLeast/atMost) not fully exported",
      outcomeId,
    );
    lines.push(
      `  // httpJson: status ok + path resolved; advanced matchers not exported`,
    );
  }
  lines.push(`}`);
  return { lines, exported: true };
}

/* ----- helpers ----- */

function oneLine(s: string): string {
  return s.replaceAll(/\s+/g, " ").trim();
}

function escapeRegex(s: string): string {
  return s.replaceAll(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function safeIdent(name: string): string {
  const cleaned = name.replaceAll(/[^A-Za-z0-9_$]/g, "_");
  return /^[A-Za-z_$]/.test(cleaned) ? cleaned : `_${cleaned}`;
}

/** Used by tests + the CLI to know whether a verifier type is exportable. */
export function isExportable(v: Verifier): boolean {
  return (
    isTextVerifier(v) ||
    isNotTextVerifier(v) ||
    isUrlVerifier(v) ||
    isCountVerifier(v) ||
    isNetworkVerifier(v) ||
    isNoFailedRequestsVerifier(v) ||
    isConsoleVerifier(v) ||
    isScriptVerifier(v) ||
    isHttpJsonVerifier(v)
  );
}

/** Extension for the generated Playwright file. */
export function exportExtension(lang: ExportLang): string {
  return lang === "js" ? ".spec.js" : ".spec.ts";
}
