/**
 * Drift guard for the runner logic the Playwright export embeds: the
 * checked-in `runtimeSources.generated.ts` must equal what the live modules
 * produce. After changing one of the modules in RUNTIME_SOURCE_FILES,
 * regenerate with
 *
 *   CAIRN_UPDATE_GENERATED=1 bun run test src/core/exporters/runtimeSources.test.ts
 *
 * and format the result (`bunx oxfmt src/core/exporters/runtimeSources.generated.ts`).
 */
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";
import { afterAll, describe, expect, it } from "vitest";
import { RUNTIME_SOURCES } from "./runtimeSources.generated";
import {
  buildRuntimeSourceTs,
  inlineRuntimeModule,
  renderRuntimeModule,
  RUNTIME_MODULES,
  runtimeModuleClosure,
  runtimeModuleImports,
  WORKBOOK_MODULE,
  type RuntimeModuleName,
} from "./runtimeSources";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../..");
const GENERATED_PATH = join(here, "runtimeSources.generated.ts");

/** The type-stripped form: ES2022 modules, `.js` import specifiers. */
function buildJs(tsSource: string): string {
  const out = ts.transpileModule(tsSource, {
    compilerOptions: {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.ESNext,
      verbatimModuleSyntax: false,
      removeComments: false,
    },
  }).outputText;
  return out.replace(
    /(from ")(\.\/[A-Za-z]+)(";)/g,
    (_match, pre: string, spec: string, post: string) =>
      `${pre}${spec}.js${post}`,
  );
}

function renderGenerated(): string {
  const entries = RUNTIME_MODULES.map((name) => {
    const tsSource = buildRuntimeSourceTs(name);
    return `  ${name}: {\n    ts: ${JSON.stringify(tsSource)},\n    js: ${JSON.stringify(buildJs(tsSource))},\n  },`;
  });
  return [
    `// GENERATED by src/core/exporters/runtimeSources.test.ts — do not edit.`,
    `// Regenerate: CAIRN_UPDATE_GENERATED=1 bun run test src/core/exporters/runtimeSources.test.ts`,
    `// then: bunx oxfmt src/core/exporters/runtimeSources.generated.ts`,
    `import type { RuntimeModuleName } from "./runtimeSources";`,
    ``,
    `export const RUNTIME_SOURCES: Record<RuntimeModuleName, { ts: string; js: string }> = {`,
    ...entries,
    `};`,
    ``,
  ].join("\n");
}

describe("generated runtime sources", () => {
  it("regenerates on request", () => {
    if (process.env["CAIRN_UPDATE_GENERATED"] !== "1") return;
    // A plain write: the file is formatted afterwards.
    const { writeFileSync } = require("node:fs") as typeof import("node:fs");
    writeFileSync(GENERATED_PATH, renderGenerated());
  });

  for (const name of RUNTIME_MODULES) {
    it(`${name}: the TypeScript copy equals the live module`, () => {
      expect(
        RUNTIME_SOURCES[name].ts,
        `${name} drifted from its source: regenerate (see the header of this test)`,
      ).toBe(buildRuntimeSourceTs(name));
    });

    it(`${name}: the JavaScript copy equals the type-stripped TypeScript copy`, () => {
      expect(
        RUNTIME_SOURCES[name].js,
        `${name} (js) drifted: regenerate (see the header of this test)`,
      ).toBe(buildJs(RUNTIME_SOURCES[name].ts));
    });
  }

  it("a module only imports other runtime modules and node built-ins", () => {
    for (const name of RUNTIME_MODULES) {
      for (const lang of ["ts", "js"] as const) {
        const specs = [
          ...RUNTIME_SOURCES[name][lang].matchAll(/from "([^"]+)";/g),
        ].map((m) => m[1]!);
        for (const spec of specs) {
          expect(
            spec.startsWith("node:") ||
              /^\.\/[A-Za-z]+$/.test(spec) ||
              /^\.\/[A-Za-z]+\.js$/.test(spec),
            `${name} (${lang}) imports ${spec}`,
          ).toBe(true);
        }
      }
    }
  });

  it("modules that a single-file export inlines together declare distinct top-level names", () => {
    const inlinable = RUNTIME_MODULES.filter((name) => name !== "xlsxJudge");
    const seen = new Map<string, RuntimeModuleName>();
    for (const name of inlinable) {
      const source = inlineRuntimeModule(name, "ts");
      const declared = [
        ...source.matchAll(
          /^(?:export )?(?:async )?(?:function|const|let|class|interface|type|enum) ([A-Za-z_$][\w$]*)/gm,
        ),
      ].map((m) => m[1]!);
      for (const decl of declared) {
        const other = seen.get(decl);
        expect(
          other,
          `${decl} is declared by both ${other} and ${name}`,
        ).toBeUndefined();
        seen.set(decl, name);
      }
    }
  });

  it("dependency closure lists dependencies first", () => {
    expect(runtimeModuleClosure(["xlsxJudge"])).toEqual([
      "matchers",
      "xlsxJudge",
    ]);
    const order = runtimeModuleClosure(["responseJudge"]);
    expect(order.at(-1)).toBe("responseJudge");
    expect(order.indexOf("matchers")).toBeLessThan(
      order.indexOf("networkJudge"),
    );
    expect(runtimeModuleImports(RUNTIME_SOURCES.xlsxJudge.ts)).toContain(
      WORKBOOK_MODULE,
    );
  });

  describe("strict compile with lib ES2022 (what a generated project or an older host tsconfig sees)", () => {
    const dirs: string[] = [];
    afterAll(async () => {
      for (const dir of dirs) await rm(dir, { recursive: true, force: true });
    });

    it("every module compiles on its own, side by side", async () => {
      const dir = await mkdtemp(join(tmpdir(), "cairn-runtime-ts-"));
      dirs.push(dir);
      const files: string[] = [];
      for (const name of RUNTIME_MODULES) {
        const path = join(dir, `${name}.ts`);
        await writeFile(path, renderRuntimeModule(name, "ts"));
        files.push(path);
      }
      // The workbook reader ships as the SDK's own JS + declarations.
      for (const ext of ["js", "d.ts"]) {
        const path = join(dir, `${WORKBOOK_MODULE}.${ext}`);
        await writeFile(
          path,
          readFileSync(join(repoRoot, `src/sdk/workbook.${ext}`), "utf8"),
        );
        if (ext === "d.ts") files.push(path);
      }
      const program = ts.createProgram(files, {
        target: ts.ScriptTarget.ES2022,
        module: ts.ModuleKind.ESNext,
        moduleResolution: ts.ModuleResolutionKind.Bundler,
        lib: ["lib.es2022.d.ts", "lib.dom.d.ts"],
        types: ["node"],
        typeRoots: [join(repoRoot, "node_modules/@types")],
        strict: true,
        noUnusedLocals: true,
        noEmit: true,
        skipLibCheck: true,
      });
      const diagnostics = ts
        .getPreEmitDiagnostics(program)
        .filter((d) => d.file && !d.file.fileName.endsWith("workbook.d.ts"))
        .map(
          (d) =>
            `${
              d.file ? d.file.fileName.split("/").pop() : ""
            }: ${ts.flattenDiagnosticMessageText(d.messageText, "\n")}`,
        );
      expect(diagnostics).toEqual([]);
    }, 60_000);
  });
});
