import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { parse as parseYaml } from "yaml";
import { syntheticTraceEntries, zipOf } from "../../testing/traceZip";

/** `cairn import playwright | playwright-trace` through the real binary. */

const CAIRN = join(process.cwd(), "bin", "cairn");

async function cairn(args: string[], cwd: string) {
  const { execa } = await import("execa");
  return execa(CAIRN, args, {
    cwd,
    reject: false,
    env: { CAIRN_LOG_LEVEL: "silent", NO_COLOR: "1" },
  });
}

describe("cairn import", () => {
  it("playwright: json report with coverage, --test and --out", async () => {
    const dir = await mkdtemp(join(tmpdir(), "cairn-import-cli-"));
    await writeFile(
      join(dir, "a.spec.ts"),
      `import { test, expect } from "@playwright/test";
test("first", async ({ page }) => { await page.goto("/one"); });
test("second", async ({ page }) => {
  await page.goto("/two");
  await expect(page.getByText("Two")).toBeVisible();
});
`,
    );
    const run = await cairn(
      [
        "import",
        "playwright",
        "a.spec.ts",
        "--test",
        "second",
        "--out",
        "second.yml",
        "--json",
      ],
      dir,
    );
    expect(run.exitCode, run.stderr).toBe(0);
    const report = JSON.parse(run.stdout) as {
      status: string;
      coverage: { mapped: number; unmapped: number };
      path: string;
    };
    expect(report.status).toBe("written");
    expect(report.coverage).toMatchObject({ mapped: 2, unmapped: 0 });
    const spec = parseYaml(await readFile(join(dir, "second.yml"), "utf8")) as {
      steps: unknown[];
    };
    expect(spec.steps).toEqual([{ open: "/two" }]);
  });

  it("playwright-trace: --stdout prints only the YAML; a non-trace exits 2", async () => {
    const dir = await mkdtemp(join(tmpdir(), "cairn-import-cli-"));
    const password = ["pw", process.pid, Date.now()].join("-");
    const token = ["tk", process.pid, Date.now()].join("_");
    await writeFile(
      join(dir, "t.zip"),
      zipOf(syntheticTraceEntries({ password, token })),
    );
    const out = await cairn(
      ["import", "playwright-trace", "t.zip", "--stdout"],
      dir,
    );
    expect(out.exitCode, out.stderr).toBe(0);
    expect(
      out.stdout.startsWith("# Generated by `cairn import playwright-trace`"),
    ).toBe(true);
    expect(out.stdout).not.toContain(password);
    expect(out.stdout).not.toContain(token);

    const named = await cairn(
      [
        "import",
        "playwright-trace",
        "t.zip",
        "--name",
        "Card flow",
        "--format",
        "json",
      ],
      dir,
    );
    expect(named.exitCode, named.stderr).toBe(0);
    const report = JSON.parse(named.stdout) as {
      path: string;
      check: { lint: { findings: Array<{ rule: string }> } };
    };
    expect(report.path.endsWith("card_flow.yml")).toBe(true);
    expect(await readFile(report.path, "utf8")).toContain("name: card_flow");

    await writeFile(join(dir, "bad.zip"), "not a zip");
    const bad = await cairn(["import", "playwright-trace", "bad.zip"], dir);
    expect(bad.exitCode).toBe(2);
    expect(bad.stderr).toContain("cairn import playwright-trace:");
  });
});
